apiVersion: v1
kind: Namespace
metadata:
  name: liga

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: liga-wiedzy
  name: liga-wiedzy
spec:
  containers:
    - name: apache
      image: mateoo/php-7.2-pdo
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-dir
          mountPath: "/var/www/html"
    - name: liga-db
      image: mysql:8.0
      args:
        - --default-authentication-plugin=mysql_native_password
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: Dev321
        - name: MYSQL_DATABASE
          value: test_db
        - name: MYSQL_INITDB_FILES
          value: /docker-entrypoint-initdb.d/init.sql
      volumeMounts:
        - name: shared-dir
          mountPath: /docker-entrypoint-initdb.d
  initContainers:
    - name: git-clone
      image: alpine/git
      command: ['sh', '-c', 'git clone https://github.com/mateoo1/Liga-wiedzy.pl.git && mv Liga-wiedzy.pl/* /data']
      volumeMounts:
        - name: shared-dir
          mountPath: /data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: shared-dir
      emptyDir: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: liga-wiedzy
  labels:
    app: liga-wiedzy
spec:
  type: ClusterIP
  selector:
    app: liga-wiedzy
  ports:
    - name: http
      port: 80
      targetPort: 80
