apiVersion: apps/v1
kind: Deployment
metadata:
  name: liga-mysql
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liga-mysql
  template:
    metadata:
      labels:
        app: liga-mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
          volumeMounts:
            - name: shared-storage
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: liga-shared-pvc
