apiVersion: v1
kind: Service
metadata:
  name: liga-mysql
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: liga-mysql
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  type: ClusterIP